### PR TITLE
IPv6 and ICMPv6 packet support

### LINKED ISSUE #8: IPv6 and ICMPv6 support
I notice there's a link in the documentation to a blog (from 11 years ago) with IPv6 and ICMPv6 modules as a patch... but these could easily be available on CPAN (and probably more up to date). I'm willing to work on this, would you prefer a PR to this dist or for me to release it as a separate dist?

### PR DESCRIPTION
**Pull request by Grinnz**
This is still a work in progress so you may want to wait to merge it. Currently it will die if an ESP extension header is encountered in encode or decode because this has a different (complex) format from every other extension header. I also intend to implement ICMPv6.

Fixes #8

### CODE REVIEW

**Comment by Grinnz** [comment]
Also note this will require a new enough version of Socket for the inet_pton/inet_ntop support, I'm not sure what version is required for that yet.

**Comment by Grinnz** [comment]
It looks like the version of Socket required for inet_pton/ntop is 1.87 (which comes with perl 5.12).

**Comment by yanick** [comment]
I can totally live w/ that updated version of Socket. :-)

**Comment by Grinnz** [comment]
You should probably change the default branch of the repo to master, I accidentally made the pull request against the releases branch since that was the default, I fixed it now.

**Comment by Grinnz** [comment]
Since the ESP header encrypts most of itself and encapsulates any further headers as well as the payload data, it will just be considered the payload data itself. I believe this is now ready.

**Comment by Grinnz** [comment]
I also added support for TCP and UDP checksums using IPv6 objects, since the checksum is done differently in those cases.

**Comment by Grinnz** [comment]
There's one remaining issue; the checksums for ICMPv6/TCP/UDP must be calculated with the final destination address which may be different from the IPv6 packet's dest_ip field if a routing header is present. To solve this requires parsing several different types of routing headers, so I will leave it for a separate task.

**Comment by yanick** [comment]
Took me a long time, but I'm finally merging to master and deploying. Thanks!

**Comment by jdluckey** [comment]
Seems like code mentioned in this issue may be linked to the issue i just opened about NetPacket::IPv6.pm creating an incorrect pseudo header.  #16

**Pull request closed without merging**
